apiVersion: v2
name: hajimari
description: A beautiful & customizable browser startpage/dashboard with Kubernetes application discovery
type: application
version: 0.1.0
dependencies:
  - name: hajimari
    repository: https://hajimari.io
    version: 2.0.2
