#
# IMPORTANT NOTE
#
# This chart inherits from the bjw-s library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
#
hajimari:
  image:
    # -- image repository
    repository: ghcr.io/toboshii/hajimari
    # -- image pull policy
    pullPolicy: IfNotPresent
    # -- image tag
    tag: v0.3.1

  # -- environment variables.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: UTC

  # -- Configures Hajimari settings for this instance.
  # @default -- See below
  hajimari:
    # -- The name of this instance, this allows running multiple
    # instances of Hajimari on the same cluster
    instanceName: null

    # -- Set to true to show all discovered applications by default.
    defaultEnable: false

    # -- Namespace selector to use for discovering applications
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: Exists

    # -- Override the title of the Hajimari pages
    title: Hajimari

    showGreeting: false

    # -- Add custom applications to the discovered application list
    customApps: []
    # - group: Media
    #   apps:
    #     - name: Test
    #       url: 'https://example.com'
    #       icon: 'mdi:test-tube'
    #       info: This is a test app

    # -- Set default bookmarks
    globalBookmarks: []
    # - group: Communicate
    #   bookmarks:
    #   - name: Discord
    #     url: 'https://discord.com'
    #   - name: Gmail
    #     url: 'http://gmail.com'
    #   - name: Slack
    #     url: 'https://slack.com/signin'

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 3000

  # -- Configures service account needed for reading k8s ingress objects
  # @default -- See below
  serviceAccount:
    # -- Create service account
    create: true

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
      ingressClassName: "nginx"
      hosts:
        - host: &host apps.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: 3000
      tls:
        - secretName: hajimari-tls
          hosts:
            - *host

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    data:
      enabled: false
      type: pvc
      accessMode: ReadWriteOnce
      size: 20Mi
