apiVersion: v2
name: kube-prometheus-stack
description: A helm chart for an app
type: application
version: 31.0.0
dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 56.9.0
