apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ntfy-basic-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: ntfy-basic-auth
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: ntfy_basic_auth
