crossplane:
  leaderElection: false

  provider:
    packages:
      - xpkg.upbound.io/upbound/provider-aws-iam:v1.9.1

  configuration:
    packages: []

  functions:
    packages:
      - xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1
      - xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.4.1
      - xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.6.0
      - xpkg.upbound.io/crossplane-contrib/function-extra-resources:v0.0.3

  metrics:
    enabled: true

  extraObjects:
    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: aws-credentials
      spec:
        secretStoreRef:
          kind: ClusterSecretStore
          name: gitlab-secret-store
        target:
          name: aws-credentials
          creationPolicy: Owner
        data:
          - secretKey: credentials
            remoteRef:
              key: crossplane_aws_credentials
    - apiVersion: aws.crossplane.io/v1beta1
      kind: ProviderConfig
      metadata:
        name: aws
      spec:
        assumeRoleARN: arn:aws:iam::964066691632:role/administrator
        credentials:
          source: Secret
          secretRef:
            namespace: crossplane-system
            name: aws-credentials
            key: credentials
