apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: {{ .Values.gateways.internet.name }}
  labels:
    name: {{ .Values.gateways.internet.name }}
spec:
  forProvider:
    region: {{ .Values.region }}
    vpcIdSelector:
      matchLabels:
        name: {{ .Values.vpc.name }}
    tags:
      - key: Name
        value: {{ .Values.gateways.internet.name }}
  providerConfigRef:
    name: aws
