apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: rds
  labels:
    name: rds
spec:
  forProvider:
    region: {{ .Values.region }}
    description: Subnet for RDS
    subnetIdSelector:
      matchLabels:
        type: private
  providerConfigRef: 
    name: aws
---
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: rds
  labels:
    name: rds
spec:
  forProvider:
    region: {{ .Values.region }}
    allocatedStorage: 20
    autogeneratePassword: true
    availabilityZone: {{ .Values.region }}a
    backupRetentionPeriod: 0
    dbInstanceClass: db.t3.micro
    dbName: rds
    dbSubnetGroupNameSelector:
      matchLabels:
        name: rds
    enableIAMDatabaseAuthentication: true
    engine: postgres
    masterUsername: crossplane
    masterUserPasswordSecretRef:
      key: password
      name: rds-password
      namespace: crossplane-system
    publiclyAccessible: false
    skipFinalSnapshot: true
    tags:
      - key: Name
        value: rds
    vpcSecurityGroupIDSelector:
      matchLabels:
        {{- toYaml .Values.securityGroups.labels | nindent 8 }}
  providerConfigRef: 
    name: aws
  writeConnectionSecretToRef:
    name: rds-credentials
    namespace: crossplane-system
