apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: aws-credentials
    creationPolicy: Owner
  data:
    - secretKey: credentials 
      remoteRef: 
        key: crossplane_aws_credentials
