#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#
homer:
  image:
    # -- image repository
    repository: b4bz/homer
    # @default -- chart.appVersion
    tag: v23.05.1
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- environment variables.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: Europe/Paris

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 8080

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: terence.cloud
      hosts:
        - host: homer.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                name: http
                port: 8080
      tls:
        - secretName: homer-tls
          hosts:
            host: homer.terence.cloud

  securityContext:
    # -- Specify the user ID the application will run as
    runAsUser: 1000
    # -- Enable validation that the container must run as non-root user
    runAsNonRoot: true
    # -- Specify the group ID the application will run as
    runAsGroup: 1000

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: false
      mountPath: /www/assets

  configmap:
    config:
      # -- Store homer configuration as a ConfigMap
      enabled: false
      # -- Homer configuration. See [image documentation](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md) for more information.
      # @default -- See values.yaml
      data:
        config.yml: |
          externalConfig: https://raw.githubusercontent.com/bastienwirtz/homer/main/public/assets/config.yml.dist
