crossplane:
  leaderElection: false

  provider:
    packages:
      - crossplane/provider-aws:master
      # - crossplane/provider-sql:master
      # - crossplane/provider-terraform:master
      # - crossplane/provider-jet-aws:v0.4.0-preview

  configuration:
    packages: []

  metrics:
    enabled: true
