openebs:
  release:
    version: "4.1.0"

  # Legacy components will be installed if it is enabled.
  # Legacy components are - admission-server, maya api-server, snapshot-operator
  # and k8s-provisioner
  legacy:
    enabled: false

  image:
    pullPolicy: IfNotPresent
    repository: ""

  mayastor:
    enabled: true

  localpv-provisioner:
    enabled: true
    openebsNDM:
      enabled: true
    hostpathClass:
      enabled: true
      name: openebs-hostpath
      basePath: "/mnt/mx500/k8s/openebs/local"
      reclaimPolicy: Retain
      isDefaultClass: true

  zfs-localpv:
    enabled: false

  lvm-localpv:
    enabled: false

  nfs-provisioner:
    enabled: false

  engines:
    local:
      lvm:
        enabled: false
      zfs:
        enabled: false
    replicated:
      mayastor:
        enabled: true
