apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-data
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: immich-library
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgresql-data
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: immich-postgresql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
