apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-library-data
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mx500/immich-test-data"
