# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
app-template:
  # defaultPodOptions:
  #   nodeSelector:
  #     kubernetes.io/hostname: homelab2
  #   automountServiceAccountToken: false
  #   securityContext:
  #     runAsUser: 568
  #     runAsGroup: 568
  #     fsGroup: 568
  #     fsGroupChangePolicy: "OnRootMismatch"

  controllers:
    # Configure the main controller
    main:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        # Configure the main application container
        main:
          image:
            repository: wolveix/satisfactory-server
            tag: v1.9.2
          env:
            TZ: Europe/Paris
          ports:
            - name: stsf-udp
              containerPort: 7777
              protocol: UDP
            - name: stsf-tcp
              containerPort: 7777
              protocol: TCP
            - name: frm
              containerPort: 8080
              protocol: TCP
          probes:
            startup:
              enabled: true
              custom: true
              spec:
                initialDelaySeconds: 60
                timeoutSeconds: 1
                periodSeconds: 5
                failureThreshold: 30
                exec:
                  command:
                    - /bin/bash
                    - -c
                    - chmod +x /healthcheck.sh && if [[ "$(/healthcheck.sh)" != true ]]; then exit 1; fi
            liveness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - /bin/bash
                    - -c
                    - if [[ "$(/healthcheck.sh)" != true ]]; then exit 1; fi
            readiness:
              enabled: true
              custom: true
              spec:
                exec:
                  command:
                    - /bin/bash
                    - -c
                    - if [[ "$(/healthcheck.sh)" != true ]]; then exit 1; fi
        sftp:
          image:
            repository: atmoz/sftp
            tag: latest
          env:
            TZ: Europe/Paris
          args:
            - "satisfactory:$5$QXWaERQfCbhenZUo$gmFbTEx0oHuFTeYR1VM9cKNSfbs5o8MFFq9sioFOp14:e:1000:1000"
          ports:
            - name: sftp
              containerPort: 22
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: 22
            readiness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: 22
      statefulset:
        volumeClaimTemplates:
          - name: config
            accessMode: ReadWriteOnce
            size: 100Gi
            advancedMounts:
              main:
                - path: /config
              sftp:
                - path: /home/satisfactory/satisfactory
    frm:
      type: deployment
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        # Configure the main application container
        companion:
          image:
            repository: featheredtoast/ficsit-remote-monitoring-companion
            tag: latest
          env:
            TZ: Europe/Paris
            FRM_HOST: satisfactory-server-frm
            FRM_PORT: 8080
          ports:
            - name: metrics
              containerPort: 9000
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /metrics
                  port: 9000
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /metrics
                  port: 9000
        cache:
          image:
            repository: featheredtoast/ficsit-remote-monitoring-cache
            tag: latest
          env:
            TZ: Europe/Paris
            FRM_HOST: satisfactory-server-frm
            FRM_PORT: 8080
            PG_HOST:
              valueFrom:
                secretKeyRef:
                  name: satisfactory-server-cnpg-cluster-app
                  key: host
            PG_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: satisfactory-server-cnpg-cluster-app
                  key: password
            PG_USER:
              valueFrom:
                secretKeyRef:
                  name: satisfactory-server-cnpg-cluster-app
                  key: user
            PG_DB:
              valueFrom:
                secretKeyRef:
                  name: satisfactory-server-cnpg-cluster-app
                  key: dbname
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /metrics
                  port: 9000
            readiness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  path: /metrics
                  port: 9000

  service:
    # Configure a service for the main application
    main:
      controller: main
      type: LoadBalancer
      ports:
        stsf-udp:
          port: 7777
          protocol: UDP
        stsf-tcp:
          port: 7777
          protocol: TCP
    frm:
      controller: main
      ports:
        frm:
          port: 8080
    sftp:
      controller: main
      type: LoadBalancer
      ports:
        sftp:
          targetPort: sftp
          port: 2222
    frmcompanion:
      controller: frm
      ports:
        metrics:
          port: 9000

  serviceMonitor:
    frm:
      enabled: true
      serviceName: satisfactory-server-frmcompanion
      endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 15s
          scrapeTimeout: 10s

cnpg-cluster:
  type: postgresql
  mode: standalone
  cluster:
    instances: 1
    imageName: "ghcr.io/cloudnative-pg/postgresql:16.3"
    storage:
      size: 10Gi
    resources: {}
    primaryUpdateMethod: switchover
    primaryUpdateStrategy: unsupervised
    logLevel: "info"
    roles: []
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
    postgresql: {}
    initdb:
      database: frm
