apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  creationTimestamp: null
  name: k0s
spec:
  api:
    externalAddress: 100.89.6.102
    address: 100.89.6.102
    k0sApiPort: 9443
    port: 6443
    sans:
      - 100.89.6.102
      - 172.18.0.1
      - 172.17.0.1
      - 10.0.0.47
      - homelab
      - homelab.snow-delta.ts.net
      - fe80::6e4b:90ff:feea:561f
      - fd7a:115c:a1e0:ab12:4843:cd96:6259:666
      - fe80::ebbb:ea3b:7f42:7a5f
      - fe80::42:78ff:fe53:a82e
      - fe80::8806:e8ff:fee8:40c7
      - fe80::2830:9cff:fe52:7c4b
      - fe80::b836:23ff:fe59:1a2d
      - fe80::6c22:93ff:fe4d:ba28
      - fe80::80e3:56ff:fe6c:5506
      - fe80::c8d0:e1ff:fe7f:a725
      - fe80::7cd4:e5ff:fe5f:c5be
      - fe80::1c2b:5ff:fee0:7587
      - fe80::54:66ff:fe0f:3d44
      - fe80::1c46:79ff:feae:bb94
      - fe80::84d7:b8ff:fe62:cd15
      - fe80::1863:7eff:fe1b:f1a3
      - fe80::c8fe:beff:fe80:c725
      - fe80::a44a:98ff:fed2:4f23
      - fe80::f8f5:27ff:fe2c:2e35
      - fe80::8c79:5ff:fe8d:e19
      - fe80::1c17:a5ff:fe50:c8c1
      - fe80::24cf:9aff:feab:eed8
      - fe80::484c:bdff:fecb:645a
      - fe80::8cd9:61ff:fefb:5b49
      - fe80::84ff:a3ff:fe7d:fb9a
      - fe80::5874:f9ff:fea0:e7c3
      - fe80::c01c:32ff:fe56:4798
      - fe80::b432:a7ff:fe25:ec09
      - fe80::1802:eaff:fee6:8783
      - fe80::470:37ff:fe17:13ed
      - fe80::6c6b:11ff:fe60:1d92
  controllerManager: {}
  extensions:
    helm:
      charts: null
      concurrencyLevel: 5
      repositories: null
    storage:
      create_default_storage_class: true
      type: openebs_local_storage
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    provider: custom
    clusterDomain: cluster.local
    dualStack: {}
    kubeProxy:
      disabled: true
    nodeLocalLoadBalancing:
      enabled: false
      envoyProxy:
        apiServerBindPort: 7443
        konnectivityServerBindPort: 7132
      type: EnvoyProxy
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
  scheduler: {}
  storage:
    etcd:
      externalCluster: null
      peerAddress: 100.89.6.102
    type: etcd
  telemetry:
    enabled: false
