apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  creationTimestamp: null
  name: k0s
spec:
  api:
    address: 192.168.1.31
    k0sApiPort: 9443
    port: 6443
    sans:
    - 192.168.1.31
    - 172.18.0.1
    - 172.19.0.1
    - 172.22.0.1
    - 172.20.0.1
    - 172.17.0.1
    - 100.75.180.13
    - fe80::987c:cf64:426a:4e6
    - fe80::42:35ff:fec5:670a
    - fe80::42:41ff:fec9:8efd
    - fe80::42:dff:fe9d:22fb
    - fe80::42:6aff:feb5:37f5
    - fe80::d07e:2ff:fe4b:db1b
    - fe80::8c3a:a5ff:fe93:d39c
    - fe80::209f:deff:fec4:213c
    - fe80::5027:ccff:fed2:517
    - fe80::9480:bfff:fe15:ebeb
    - fe80::6c4e:18ff:fead:f736
    - fe80::bc34:f7ff:fed4:aad9
    - fe80::4865:fff:fe0d:b5c0
    - fe80::e859:5fff:fed3:5f25
    - fe80::6ceb:9cff:fe6a:b3b3
    - fe80::f850:30ff:fe9f:de90
    - fe80::8ce7:4aff:fe9d:1088
    - fe80::f0eb:8bff:fea2:1905
    - fe80::48d8:5ff:fe29:d7f4
    - fe80::e4ed:d9ff:fed2:50d3
    - fd7a:115c:a1e0::a501:b40d
    - fe80::ceef:d0ff:eae1:f67d
  controllerManager: {}
  extensions:
    helm:
      charts: null
      concurrencyLevel: 5
      repositories: null
    storage: {}
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    calico: null
    clusterDomain: cluster.local
    dualStack: {}
    kubeProxy:
      iptables:
        minSyncPeriod: 0s
        syncPeriod: 0s
      ipvs:
        minSyncPeriod: 0s
        syncPeriod: 0s
        tcpFinTimeout: 0s
        tcpTimeout: 0s
        udpTimeout: 0s
      metricsBindAddress: 0.0.0.0:10249
      mode: iptables
    kuberouter:
      autoMTU: true
      hairpin: Enabled
      ipMasq: false
      metricsPort: 8081
      mtu: 0
      peerRouterASNs: ""
      peerRouterIPs: ""
    nodeLocalLoadBalancing:
      envoyProxy:
        apiServerBindPort: 7443
        konnectivityServerBindPort: 7132
      type: EnvoyProxy
    podCIDR: 10.244.0.0/16
    provider: kuberouter
    serviceCIDR: 10.96.0.0/12
  scheduler: {}
  storage:
    etcd:
      externalCluster: null
      peerAddress: 192.168.1.31
    type: etcd
  telemetry:
    enabled: false
