apiVersion: v2
name: k8tz
description: Kubernetes admission controller and a CLI tool to inject timezones into Pods and CronJobs
type: application
version: 0.2.3
dependencies:
  - name: k8tz
    repository: https://k8tz.github.io/k8tz/
    version: 0.16.2
