apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "dead-drop.fullname" . }}-purge-drops
  labels:
    {{- include "dead-drop.labels" . | nindent 4 }}
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - purge
              envFrom:
                - configMapRef:
                    name: {{ include "dead-drop.fullname" . }}
          restartPolicy: OnFailure
          serviceAccountName: {{ include "dead-drop.serviceAccountName" . }}
