apiVersion: v1
items:
  - apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: alertmanager-bot
      namespace: monitoring
    spec:
      encryptedData:
        admin: AgBL6mycmo0KRIBt4JjoMySeJV1VhzsWQO8cxEN0RlilyuuFUZatIswrV1XSFfuFy1DaPJ4jb/UlhXM/kGlzrMsCy1/WEhPC2HU4seiSjdqRuUlj68OP/AgDjB3NIfR7fzZMHO0q7MpYMH0YTcDnBJobmQ5aCOIgeaj6Gu6js/E/ZjWE1P4Mw4WcNCU/cDTnuapDTMm63V0cXxPQtQMgerMYEtKLBowRGB+YFsu1jotVPd/CCrI90//UBqt7Ji99nFMB8HHQORhEyMkvM8eMpmu19QIPP7udsgaRtu2kNWhXXU0/g6L9TSw8mGDZkcPCW0/iBSgrf0NW4SM5U0BK57TIE+i2I30pyUXk+YBPY/3Vq7ZU3tzSXDNabXCSo8zwMbslk+Eb9GAWIFFo0cdNPak13HZDdkT9JbHlDWfbPZBnRSMc3bWj6Qd/GTodqaYY+dN/8O5n1Aycpa8SRtVs+RUtv/VZVok5QtkDL8lGJDjt1SE1CuX9jpQl8vtbPN7c9c8/pBafSyq5UWmC1j/Sm6dzpvnz3YZWbhMjMfowGMB7OgtvTl0QJ+fXIu0qmbBh/VC6of5wIaGDJo+dRRGrMUvgQCfSg383pd40YDgRuo7fNDL7LqdcXIg903ZGg2w0CK+LORF00AkFCV834Dzeymgt2taOGzg3zBGHMwOjCzRcY+IC7k8iX3IaR3KNAQ+Huoo1Qz93/icslu7h
        token: AgC0CRwMs14Ur0oWDeKKxUusTkq4VFEipGJ7gMnKo+oSaz5puwCvogAcY8fKhPElessFViLyZjTeTT+fHmvZ7ZnvH7PaXdHK1DUOyNfqMD5yNNYDa7+X/qR+EU2BnvHxFhKcyffC/z6RzOpV/7an+yuUkT+Bb9qKvpylxFWiCkNtyw9KpraEsqRDRQEdJlTGpr/k2MDxwmlxqiiPLUSY9m+SZ2sHeCe4JIlFKfWY2xPiwegMQjLqQTc561zRkJMOJG+jJjZkdeTNJB15mjy966sHSb1MayT0qmCpDXdSCOGoIycEmrG64dTj97RIP1QRLzldp7cZgL1TKk+xmnvOK52hF+d3fS2Lc90PaSy+CiYiGNTMCKHcLcFTiLRzMIM2qwfejqIlILoRiwbMbhS8xQd+8sY5mWlm2Xy1EkBa0qrQ3AR7wFKTaE3zrLs1GFtj+T+Dua4QRLeDBGUb3Q6t2XoupzRBXbQ7YJKv6/W8yy0zZPX4vc9jJWZi8xJeiwXpsmY4oKF85uDbngYFCbdyehotHbSWlen8l/hJhjrOh+8mLICjd7pbdpI2YAKdgWX2E/4CA/yYSQBYe8Icug5lldJHU7cqwUvBVuXmIXCFjV47SMPPtcrC74Ja387Z4bJZ1afFFRTp6jkovcU6vNXhuU13RStmcgZBdfT9T9vVDLjTA1oQt/MI6XbhW6l3ub5+ujAudCWtYNLSvkS71oYWgXoWbLR1hy+Ooz8R9kziEzdFkBU7aYO8RC/HGKBqLayf
      template:
        data: null
        metadata:
          creationTimestamp: null
          labels:
            app.kubernetes.io/name: alertmanager-bot
          name: alertmanager-bot
          namespace: monitoring
        type: Opaque
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-bot
      name: alertmanager-bot
      namespace: monitoring
    spec:
      ports:
        - name: http
          port: 8080
          targetPort: 8080
      selector:
        app.kubernetes.io/name: alertmanager-bot
  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager-bot
      name: alertmanager-bot
      namespace: monitoring
    spec:
      podManagementPolicy: OrderedReady
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: alertmanager-bot
      serviceName: alertmanager-bot
      template:
        metadata:
          labels:
            app.kubernetes.io/name: alertmanager-bot
          name: alertmanager-bot
          namespace: monitoring
        spec:
          containers:
            - args:
                - --alertmanager.url=http://alertmanager-operated:9093
                - --log.level=info
                - --store=bolt
                - --bolt.path=/data/bot.db
              env:
                - name: TELEGRAM_ADMIN
                  valueFrom:
                    secretKeyRef:
                      key: admin
                      name: alertmanager-bot
                - name: TELEGRAM_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: token
                      name: alertmanager-bot
              image: metalmatze/alertmanager-bot:0.4.3
              imagePullPolicy: IfNotPresent
              name: alertmanager-bot
              ports:
                - containerPort: 8080
                  name: http
              resources:
                limits:
                  cpu: 100m
                  memory: 128Mi
                requests:
                  cpu: 25m
                  memory: 64Mi
              volumeMounts:
                - mountPath: /data
                  name: data
          restartPolicy: Always
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: alertmanager-bot-alertmanager-bot-0
      volumeClaimTemplates:
        - apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            labels:
              app.kubernetes.io/name: alertmanager-bot
            name: alertmanager-bot
            namespace: monitoring
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: longhorn
kind: List
