apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: {{ .Values.bastion.name }}
  labels:
    name: {{ .Values.bastion.name }}
spec:
  forProvider:
    region: {{ .Values.region }}
    description: Bastion security group
    groupName: {{ .Values.bastion.name }}
    vpcIdSelector:
      matchLabels:
        name: {{ .Values.vpc.name}}
    tags:
      - key: Name
        value: {{ .Values.bastion.name }}
    egress:
      - ipProtocol: "-1"
        ipRanges:
          - cidrIp: 0.0.0.0/0
  providerConfigRef:
    name: aws
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: {{ .Values.eks.cluster.name }}
  labels:
    name: {{ .Values.eks.cluster.name }}
spec:
  forProvider:
    region: {{ .Values.region }}
    description: Cluster security group
    groupName: {{ .Values.eks.cluster.name }}
    vpcIdSelector:
      matchLabels:
        name: {{ .Values.vpc.name}}
    tags:
      - key: Name
        value: {{ .Values.eks.cluster.name }}
    ingress:
      - ipProtocol: "-1"
        userIdGroupPairs:
          - groupIdSelector:
              matchLabels:
                name: {{ .Values.bastion.name }}
    egress:
      - ipProtocol: "-1"
        ipRanges:
          - cidrIp: 0.0.0.0/0
  providerConfigRef:
    name: aws
