apiVersion: v2
name: cnpg
description: A helm chart for an app
type: application
version: 0.1.0
dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.22.0
