# velero restore create --from-backup velero-default-xxx --namespace-mappings xxx:xxx-bkp --resource-modifier-configmap remove-argocd-instance-label
apiVersion: v1
kind: ConfigMap
metadata:
  name: remove-argocd-instance-label
data:
  cm.yaml: |
    version: v1
    resourceModifierRules:
      - conditions:
          groupResource: "*"
          resourceNameRegex: ".*"
        patches:
          - operation: remove
            path: "/metadata/labels/argocd.argoproj.io~1instance"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-policy
data:
  cm.yaml: |
    version: v1
    volumePolicies:
      - conditions:
          volumeTypes:
            - emptyDir
            - downwardAPI
            - configmap
            - cinder
        action:
          type: skip
