apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner-registration-token
spec:
  
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: gitlab-runner-registration-token
    creationPolicy: Owner
  dataFrom:
    - extract: 
        key: gitlab_runner_registration_token
