apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gitlab-runner-registration-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: gitlab-runner-registration-token
    creationPolicy: Owner
  dataFrom:
    - key: gitlab_runner_registration_token
