ingress-nginx:
  controller:
    service:
      # Forces MetalLB to set this IP
      loadBalancerIP: "192.168.1.240"

    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
