# https://github.com/linkerd/linkerd2/issues/6561
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkerd-identity-issuer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: linkerd-identity-issuer
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: linkerd_identity_issuer_crt
    - secretKey: tls.key
      remoteRef:
        key: linkerd_identity_issuer_key
