apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: ingress-nginx
            namespace: ingress-nginx
          - name: argocd
            namespace: argocd
          - name: external-dns
            namespace: external-dns
          - name: cert-manager
            namespace: cert-manager
          - name: oauth2-proxy
            namespace: oauth2-proxy
          - name: dead-drop
            namespace: dead-drop
          - name: immich
            namespace: immich
          - name: velero
            namespace: velero
          - name: reloader
          - name: openebs
            namespace: openebs
          - name: nextcloud
            namespace: nextcloud
          - name: external-endpoints
            namespace: external-endpoints
          - name: httpbin
            namespace: httpbin

    - list:
        elements:
          - name: external-secrets
            namespace: external-secrets
        template:
          metadata: {}
          spec:
            project: ""
            source:
              repoURL: ""
            # caBundle injection breaks the sync loop.
            ignoreDifferences:
              - group: admissionregistration.k8s.io
                kind: "*"
                jqPathExpressions:
                  - .webhooks[].clientConfig.caBundle
              - group: apiextensions.k8s.io
                kind: "*"
                jsonPointers:
                  - /spec/conversion/webhook/clientConfig
            destination: {}
            syncPolicy:
              syncOptions:
                - CreateNamespace=true
                - RespectIgnoreDifferences=true


  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
        # argocd.argoproj.io/compare-options: ServerSideDiff=true
    spec:
      project: default
      source:
        repoURL: git@github.com:cterence/homelab-gitops.git
        targetRevision: HEAD
        path: "k8s-apps/{{ .name }}"
      destination:
        name: in-cluster
        namespace: {{ ternary .namespace .name (hasKey . "namespace") }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          # - ServerSideApply=true
