apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: argocd
          - name: calibre-web
          - name: cert-manager
          - name: cloudnative-pg
            namespace: cnpg-system
            serverSideApply: true
          - name: dead-drop
          - name: external-dns
          - name: external-secrets
          - name: httpbin
          - name: immich
          - name: ingress-nginx
          - name: kube-prometheus-stack
            namespace: monitoring
            serverSideApply: true
          - name: loki
          - name: nextcloud
          - name: oauth2-proxy
          - name: openebs
          - name: reloader
          - name: tailout
          - name: tailscale-operator
          - name: vaultwarden
          - name: velero

  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "."
        notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
        argocd.argoproj.io/compare-options: "{{ printf \"%s=%s\" \"ServerSideDiff\" (dig \"serverSideDiff\" \"false\" . | toString) }}"
    spec:
      project: default
      source:
        repoURL: git@github.com:cterence/homelab-gitops.git
        targetRevision: HEAD
        path: "k8s-apps/{{ .name }}"
      destination:
        name: in-cluster
        namespace: "{{ default .name (dig \"namespace\" \"\" .) }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - "{{ printf \"%s=%s\" \"ServerSideApply\" (dig \"serverSideApply\" \"false\" . | toString) }}"
