oauth2-proxy:
  config:
    existingSecret: gitlab-oauth2-credentials
    # Configuring email_domains as an empty array acts as a deny all
    configFile: |-
      email_domains = []

  extraArgs:
    # For ingress-nginx
    set-xauthrequest: true

    # Gitlab
    provider: gitlab

    # Google
    # provider: google

    # Nextcloud
    # provider: nextcloud
    # login-url: https://next.terence.cloud/index.php/apps/oauth2/authorize
    # redeem-url: https://next.terence.cloud/index.php/apps/oauth2/api/v1/token
    # validate-url: https://next.terence.cloud/ocs/v2.php/cloud/user?format=json

  authenticatedEmailsFile:
    enabled: true
    # Restrict access to specific email addresses
    restricted_access: |-
      terence.chateigne@posteo.net
      terence.chateigne@gmail.com

  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/target: terence.cloud
    className: nginx
    path: /oauth2
    pathType: Prefix
    # Every host that needs oauth authentication
    hosts:
      - alertmanager.terence.cloud
      - argocd.terence.cloud
      - atlantis.terence.cloud
      - duplicati.terence.cloud
      - grafana.terence.cloud
      - httpbin.terence.cloud
      - kibana.terence.cloud
      - loki.terence.cloud
      - longhorn.terence.cloud
      - pihole.terence.cloud
      - prometheus.terence.cloud
      - qbittorrent.terence.cloud

  metrics:
    enabled: true
    servicemonitor:
      enabled: true
