apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-client-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: keycloak-client-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef: 
        key: keycloak_argocd_client_secret
