apiVersion: v2
name: homer
description: A very simple static homepage for your server
type: application
version: 0.1.0
dependencies:
  - name: homer
    repository: https://djjudas21.github.io/charts/
    version: 8.2.0
