apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgCdg0rq2R+VXhA8GHz6Qew8aJTJnaeqtY5rJfz/OIQe/rD/QtqpjrDb4gssRhEclAaNCWR6ZnamO4kcDcqxZmXle6a/atoxNDQgIgUh0GCl8DOZ70S+rb5781neYDptXwPOa3Etyi6yKnUJR+EZ8+IFfFh149zArE7JDX/slKhInVqeRsGgcBvXj1swkfewiF/IAyss0hpcEaxQCqXou/w8uApMF7cP036SQRn9mVXnMzDhWiSBPStFdStLlFBFLiSOydhuHNB9bhQxJ1O7y8LOWQ38IEfdlh4BxcgsdA9CWo89skwnhgswBCSN10XGl6znQQ6qyjoey2V8jUuQ0KUIRcu+J+HWhvsCCZtURBqjs/spVptFI+mhEhsh0veJ07J+9HshKUtV9PhpbsxleBXzMwRy7nI+SibIUXXDhVXkE9DewLIAjbJFoGvW5wBGh58xDvYIP1/d/tdcapXigZBcdyPEQ8zBCoiNthViNKabQGQzmDqoy4ehIByYDcGSFiSmqGCcOvXLj/P03cOT+cRJ3DCHVgYBI+d8WAkIfMj/abe8HQKhZ6PWzOvc8PwyltKAz3RHV4iR8/DKLgoSdvDogAjPJoEqLACjng9SofmRu+t8QucijP/Tkw1/g0IfBz3BmQwwAXJM3hi29RqnyDVoO6pK7zSIn1YbjAQ/kbLnwyLFHnyglrIXUKXD8DBsABM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/instance: pihole-manifests
      name: pihole-secret
      namespace: pihole
    type: Opaque

