opentelemetry-operator:
  manager:
    featureGates: operator.autoinstrumentation.go
    collectorImage:
      repository: otel/opentelemetry-collector-k8s
      tag: 0.107.0
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
    createRbacPermissions: true
