opentelemetry-operator:
  manager:
    collectorImage:
      repository: otel/opentelemetry-collector-k8s
      tag: 0.114.0
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
    createRbacPermissions: true
    extraArgs:
      - --enable-go-instrumentation
