apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgCn2lQBs29u+q+5paEjMK7a4qMCCTI5DP5nzhtmel3LrTGPLJ7iLBZgu9gLzdVYU2JVxTx6z66Zzl0u8maGf6+o622XSh2kmfX9GfQ9/Np1OdXPMI6RwBvYW/ZhkDmXMgRwq2/4LG/54FCSsUrI7oPHUuonJ+3rFnCgaq+fc82bFWrPXWkBGgvzlPDy8lsvn5UzhBx+K8oFzSNppOnLfKz3ypPvITFOyfYxearc0ehSk6Wh8JQJ71CfLd5Q1TlVekJHsrKubZTipqRIRzXcMVRe5W3OSzUBEzIdENY0balb8rua02zkFhU8XZ/nCpAlcG9PAecKfonalEwxeG/75VNi9kj+3pHorbSVulvHpZEMhJ1e/CFR4NHZYHV65uaXEBHvd2Fgb24OHyvP0u/A96FbBcB+/OAJjPtCH2uH6Se5nP00SdzjSRExuvhKIpZG5hEF1HD37fbBSOYrn2kUgHHnx+UYSrZqauDQqTHiagDtohoyn14IOOU+UClZ+PpW0KWgcxARMd7GR01YigOuYtkreecvT2a1mjD7PXgqYUBZpQner5qa77D65WoN5W2SYY0VV8x/bUAcrQ2D7kYBEefJkiqENUownjyHvPWwrDhTCeh4J7sn7lslcL6BmrQLFiW2CZhMsUDQrNn+7Gd3UnBvmRGrqPiLIWoc5izo6Ic22zsqbs4QemiiZ6Ge5BGymMRTmPzDpTnziJtUMIaXDUwf3OTKvocu3+k1oPX5pskEb0bvXc5OtuLRTzCSjn9uFw/SOtO4Do9NHahx2Cb9jwbT3dYVBUjyZInpdgHkGfivybkQXFu0vS8Xv4kQyA/1b2zWzTNsfEUd+CC0zdmr7vcVh8d0pQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system
    type: Opaque

