apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: bastion
  labels:
    toto: toto
spec:
  forProvider:
    region: {{ .Values.region }}
    description: Bastion security group
    groupName: bastion
    vpcIdSelector:
      matchLabels:
        name: {{ .Values.vpc.name}}
    tags:
      - key: Name
        value: bastion
    egress:
      - ipProtocol: "-1"
        ipRanges:
          - cidrIp: 0.0.0.0/0
  providerConfigRef:
    name: aws
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: SecurityGroup
metadata:
  name: vpc-endpoint
  labels:
    name: vpc-endpoint
spec:
  forProvider:
    region: {{ .Values.region }}
    description: VPC endpoints security group
    groupName: vpc-endpoint
    ingress:
      - ipProtocol: "-1"
        userIdGroupPairs:
          - groupIdSelector:
              matchLabels:
                toto: toto
            # vpcIdSelector:
            #   matchLabels:
            #     name: {{ .Values.vpc.name }}
    egress:
      - ipProtocol: "-1"
        ipRanges:
          - cidrIp: 0.0.0.0/0
    vpcIdSelector:
      matchLabels:
        name: {{ .Values.vpc.name}}
    tags:
      - key: Name
        value: vpc-endpoint
  providerConfigRef:
    name: aws
