apiVersion: v1
kind: Service
metadata:
  name: {{ include "librephotos.fullname" . }}-backend
  labels:
    {{- include "librephotos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "librephotos.fullname" . }}-backend
