apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "librephotos.serviceAccountName" . }}-frontend
  labels:
    {{- include "librephotos.labels" . | nindent 4 }}
  {{- with .Values.frontend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
