apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: atlantis-terraform-cloud-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: atlantis-terraform-cloud-token
    creationPolicy: Owner
  data:
    - secretKey: ATLANTIS_TFE_TOKEN
      remoteRef: 
        key: atlantis_terraform_cloud_token_ATLANTIS_TFE_TOKEN
