apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-nextcloud-uploader-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: immich-nextcloud-uploader-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: immich_nextcloud_uploader_api_key
