apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-postgres-user-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: nextcloud-postgres-user-password
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_USERNAME: {{ .Values.nextcloud.externalDatabase.user }}
        DB_HOSTNAME: {{ .Values.nextcloud.externalDatabase.host }}
        DB_NAME: {{ .Values.nextcloud.externalDatabase.database }}
        DB_PASSWORD: "{{"{{ .DB_PASSWORD }}"}}"
        ADMIN_PASSWORD: "{{"{{ .ADMIN_PASSWORD }}"}}"
        REPLICATION_PASSWORD: "{{"{{ .REPLICATION_PASSWORD }}"}}"
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: nextcloud_postgres_user_password
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: nextcloud_postgres_admin_password
    - secretKey: REPLICATION_PASSWORD
      remoteRef:
        key: nextcloud_postgres_replication_password
