{{ range $application := .Values.applications }}
{{- if $application.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $application.name }}
  {{- with $application.annotations }}
  annotations:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ default "default" $application.project }}
  {{- with $application.source }}
  source:
    {{- toYaml . | nindent 6 }}
  {{- end }}
  destination:
    {{- if $application.destination.server }}
    server: https://kubernetes.default.svc
    {{- else }}
    name: in-cluster
    {{- end }}
    {{- if $application.destination.namespace }}
    namespace: {{ $application.destination.namespace }}
    {{- end }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
{{- end }}
{{- end }}
