apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test-external-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: gitlab-secret-store

  target:
    name: test-external-secret
    creationPolicy: Owner

  data:
    - secretKey: test_external_secret # Key given to the secret to be created on the cluster
      remoteRef: 
        key: test_external_secret # Key of the variable on Gitlab
