apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: url-shortener-repository-credentials
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgA8jQuIAOPDoa9uw25BU6qr3UCzf+YiW59l5V8aBqiunyAGuNcQax9FLKhIzp12KFDgxLJt0UDzek64rGsQ4/SWTCwUqtq7CKrr7AJ66EdzQ00sET0g5be8vldr5AcLLB2gSsOOM0xpQ6OyA6kolDc6tY0IR9bqmGo20azIrpy1iZzlbNdqk9haQ+jqH+/h0iZLLU6D7JM8oC3zXw+Wgcq+QKvgZK7ecyAjRIjzLhzjAYh/+tksRMtJMt8p6+Y3t9ED5izoSPZA7AWSFaos4IKZMxBnRGsukYEqrvOYrvmwXl/jbKY3pMRveF1a/nHYK0MNn6eYLJY11xusffHQXx8dtCjphDRUvw+1+7fM9DhmP5s1+2iBhPUrUgqQT/W8WLnfn1UQqjk2EBdZY6T4KQiweeVtM+WOGkuAxZwtSco/6fZk+2AG0E4uR5VHk7XD2M+IzQkAPu2/8sgIndPyBsFEdrOfvIvCsZoAUs6KhHXnsiUcCTgy+0L/O0ntZnEkDAdlMrASqZ0FXWddmcHuhJbdwceV2sDu7lWsiQNqzYxNMl6+fbBCa5PmJIKbxz4IstOKCmLpK32Dup7fMVElOWxK+i+cEkGfQanIRpn+zRakkQ4ecxftnoVGWHECFm8GMyhVnPjBKNz+4BdB2O+6LzxAKBJVuHQR+fef2cayzxw/ZsD6zVit4Nbh+2kWn4nEhsOQedkt4a6S194Ozj+dL9jwXB9RievKmLWSmmXX2jd0fl+bmeVm/xmj5E0HbHS+80z6oSv8HsgF5AafYpUVQ1DcudUz47P8WXAX6fjfYwlzAtqOs7RCDhRJ9KBSgTpfe/eLNONRn7RyGJ/d1mah1XpX6U66+F5VOFzcot4uUiFG2dYu7x9o7GfKu+2iOyZGNepWMCYe31VfveU2I7ekNpMcmccDYWuS88tfx7RFPnU1YppYwh9Rw21nvNUo5AiAnqhHN+J5LFKs9X3lfLoldSznoGKQJq1Oib7YEMEqbLtUZTzUFkJF6gxVKvVc0E4/t5nfvCtLG01T4sHr87xHr/yjASykNJfhdSVB46g6w/p85ubtPT4xiSdYbfhTj5pKE0dde1YhRKJKr/hZBgI6fpozcc7fw7ZhYzCX6oaTl6TqtC3Mvk6x6Dg8YBbrYl4WdjBz9JO96kCtfh2IeqSGjx56xT1YDwrGaaEeO9GyTd3oPmD+p+RT0sdPZ9fmEXuUrerdIriKmG/n0J1ClvcTktY=
    url: AgCM9vwZ0REddpykHymGyksCypjEsPggcjt4VN2OpteTW1mNNQVcgmtjgWnHBeXQ4Yprr0PPZAT86cvQUZmQgpvRbdwMJwpyfQMM9xzZ0dN/8YBpzH89jpR7bKBagyk62Yc6oquoHCRnPXLDs3rUKu3H6Gemqvc6C4ODHjR9NlxMVmburFZXkVwUHrYAdd6VrHeZbWRAxLt2RPpMqgpS8fEQL7AiuTaufTuj0+siET0RQUCWGA8pFrTus1KpmYrL4ftAgNfpsEUDogdHyPbKVLOS5ddAYz1bAxkKEkGDKRYxc3BZpKqyTkZ+B1ayG2/PcrQpgOjpBO6JjqKtCrJUaIaI1hJ8Jd75pRsrxzDdMS7NicE4EbQXFK1R33z8/Yb4kZHuV8A+p1NKXbkn01X58pHDoB7pA5sTK4UyAma0ic05cHF/oiZymT14Tt0HXmFaX3cxouNo7hHXjL0XgOnKzme5ooOWYtlL4jSv7CL4tasoznMTYdCM28F0a3/heAUMlVXZwRVldd4aWrjkKT8zYEqaCj/hPPZNbWEwBL/fzL3xXkHIsIsD/0SWqrH4pJrAbQw0Bq/qFnIjMWJIDGEKR47i0IrXbhkTyBvYD8qqqjOq8ae0wZkVnRqW4JHSCLuQAFVj43dX0Msse3FJaolFncvj8D6Eks6QteJNRmYWb0+2MCV44LixZIgAYuPAbTMktaHDFSKP4O1KVofLOypvfnQUIgm3fuxyl7mpIiCOASDHgUbf+S9hUEwvS2571X9gosTu
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: url-shortener-repository-credentials
      namespace: argocd
    type: Opaque

