apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
spec:
  generators:
    - list:
        elements:
          - name: ingress-nginx
            namespace: ingress-nginx
            syncWave: "1"
          - name: metallb
            namespace: metallb
            syncWave: "1"
          - name: argocd
            namespace: argocd
            syncWave: "2"
          - name: external-dns
            namespace: external-dns
            syncWave: "2"
          - name: external-secrets
            namespace: external-secrets
            syncWave: "2"
          - name: cert-manager
            namespace: cert-manager
            syncWave: "3"
          - name: oauth2-proxy
            namespace: oauth2-proxy
            syncWave: "3"
          - name: sealed-secrets
            namespace: sealed-secrets
            syncWave: "3"
          - name: longhorn
            namespace: longhorn-system
            syncWave: "4"
          - name: alertmanager-telegram
            namespace: monitoring
            syncWave: "5"
          - name: atlantis
            namespace: atlantis
            syncWave: "5"
          - name: blackbox-exporter
            namespace: monitoring
            syncWave: "5"
          - name: external-endpoints
            namespace: external-endpoints
            syncWave: "5"
          - name: gitlab-runner
            namespace: gitlab
            syncWave: "5"
          - name: httpbin
            namespace: apps
            syncWave: "5"
          - name: kube-prometheus-stack
            namespace: monitoring
            syncWave: "5"
          - name: loki-stack
            namespace: monitoring
            syncWave: "5"
          - name: metrics-server
            namespace: metrics-server
            syncWave: "5"

    # Dedicated generator for this application.
    # Needed because the source is not internal to this repo and the sync policy is not the same.
    - list:
        elements:
          - name: kube-prometheus-stack-crds
            namespace: monitoring
            syncWave: "1"
        template:
          metadata: {}
          spec:
            project: "default"
            source:
              directory:
                recurse: true
              repoURL: https://github.com/prometheus-community/helm-charts.git
              path: charts/kube-prometheus-stack/crds/
              targetRevision: kube-prometheus-stack-34.1.1
            destination: {}
            syncPolicy:
              syncOptions:
                - CreateNamespace=true
                - Replace=true

  template:
    metadata:
      name: "{{name}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "/applications/{{name}}"
        argocd.argoproj.io/sync-wave: "{{syncWave}}"
        notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1001726711150"
    spec:
      project: default
      source:
        repoURL: git@github.com:cterence/argo.git
        targetRevision: HEAD
        path: "applications/{{name}}"
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
