apiVersion: v2
name: cnpg
description: A helm chart for an app
type: application
version: 0.1.0
dependencies:
  - name: app-template
    repository: https://bjw-s.github.io/helm-charts
    version: 3.2.1
