ingress-nginx:
  controller:
    podAnnotations:
      linkerd.io/inject: "enabled"

    service:
      # Forces MetalLB to set this IP
      # loadBalancerIP: "192.168.1.240"

      # ClusterIP for use with cloudflare tunnels
      type: ClusterIP

    config:
      allow-snippet-annotations: "true"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    extraEnvs:
      - name: OC_AGENT_HOST
        value: collector.linkerd-jaeger:55678

  ingress:
    options:
      allow-snippet-annotations: "true"
