ingress-nginx:
  controller:
    replicaCount: 2
    service:
      # Forces MetalLB to set this IP
      type: LoadBalancer
      loadBalancerIP: "192.168.1.240"

    config:
      allow-snippet-annotations: "true"
      proxy-body-size: "512k"
      proxy-buffer-size: "512k"
      global-allowed-response-headers: "Request-Id"
      plugins: "crowdsec"
      lua-shared-dicts: "crowdsec_cache: 50m"
      use-proxy-protocol: "true"
      proxy-real-ip-cidr: "192.168.1.0/24"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    extraEnvs:
      - name: OC_AGENT_HOST
        value: collector.linkerd-jaeger:55678

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: '{{ include "ingress-nginx.name" . }}'
            app.kubernetes.io/instance: "{{ .Release.Name }}"
            app.kubernetes.io/component: controller
    extraInitContainers:
      - name: init-clone-crowdsec-bouncer
        image: crowdsecurity/lua-bouncer-plugin
        imagePullPolicy: IfNotPresent
        env:
          - name: API_URL
            value: "http://crowdsec-service.crowdsec.svc.cluster.local:8080"
          - name: BOUNCER_CONFIG
            value: "/crowdsec/crowdsec-bouncer.conf"
        envFrom:
          - secretRef:
              name: crowdsec-credentials
        command:
          [
            "sh",
            "-c",
            "sh /docker_start.sh; mkdir -p /lua_plugins/crowdsec/; cp -R /crowdsec/* /lua_plugins/crowdsec/",
          ]
        volumeMounts:
          - name: crowdsec-bouncer-plugin
            mountPath: /lua_plugins
    extraVolumeMounts:
      - name: crowdsec-bouncer-plugin
        mountPath: /etc/nginx/lua/plugins/crowdsec
        subPath: crowdsec
    extraVolumes:
      - name: crowdsec-bouncer-plugin
        emptyDir: {}

  ingress:
    options:
      allow-snippet-annotations: "true"

  tcp: {}
