ingress-nginx:
  controller:
    service:
      # Forces MetalLB to set this IP
      type: LoadBalancer
      loadBalancerIP: "192.168.1.240"

    config:
      allow-snippet-annotations: "true"
      proxy-body-size: "512k"
      proxy-buffer-size: "512k"
      global-allowed-response-headers: "Request-Id"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    extraEnvs:
      - name: OC_AGENT_HOST
        value: collector.linkerd-jaeger:55678

  ingress:
    options:
      allow-snippet-annotations: "true"

  tcp: {}
