ingress-nginx:
  controller:
    service:
      # Forces MetalLB to set this IP
      # loadBalancerIP: "192.168.1.240"

      # ClusterIP for use with cloudflare tunnels
      # type:

      type: NodePort
      nodePorts:
        http: 30080
        https: 30443

    config:
      allow-snippet-annotations: "true"
      proxy-body-size: "512k"
      proxy-buffer-size: "512k"
      global-allowed-response-headers: "Request-Id"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    extraEnvs:
      - name: OC_AGENT_HOST
        value: collector.linkerd-jaeger:55678

  ingress:
    options:
      allow-snippet-annotations: "true"
