apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: cloudflare-credentials
    creationPolicy: Owner
  data:
    - secretKey: cloudflare_api_token 
      remoteRef: 
        key: cloudflare_credentials_cloudflare_api_token
