apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cloudflare-credentials
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store

  target:
    name: cloudflare-credentials
    creationPolicy: Owner

  data:
    - secretKey: cloudflare_api_token # Key given to the secret to be created on the cluster
      remoteRef: 
        key: cloudflare_credentials_cloudflare_api_token # Key of the variable on Gitlab
