apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-data
spec:
  capacity:
    storage: 900Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/elements/nfs-server
  claimRef:
    namespace: nfs-server
    name: nfs-server-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - homelab2
