apiVersion: v2
name: external-dns
description: Configure external DNS servers (AWS Route53, Google CloudDNS and others) for Kubernetes Ingresses and Services
type: application
version: 6.1.3
dependencies:
  - name: external-dns
    repository: https://charts.bitnami.com/bitnami
    version: 8.3.5
