apiVersion: v2
name: external-dns
description: A helm chart for an app
type: application
version: 6.1.3
dependencies:
  - name: external-dns
    repository: https://charts.bitnami.com/bitnami
    version: 6.29.1
