external-dns:
  provider: cloudflare
  cloudflare:
    secretName: cloudflare-credentials
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  annotationFilter: external-dns.alpha.kubernetes.io/exclude notin (true)
