apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshots
spec:
  cron: "0 4 * * *"
  task: "snapshot"
  groups:
    - default
  retain: 7
  concurrency: 3
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backups
spec:
  cron: "0 6 * * *"
  task: "backup"
  groups:
    - default
  retain: 30
  concurrency: 3
