apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: go
spec:
  exporter:
    endpoint: http://opentelemetry-collector.opentelemetry-collector:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
