apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: tailscale-auth
    creationPolicy: Owner
  data:
    - secretKey: TS_AUTHKEY
      remoteRef:
        key: tailscale_auth
