apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: terence.chateigne@posteo.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
            ingressTemplate:
              metadata:
                annotations:
                  external-dns.alpha.kubernetes.io/target: terence.cloud
                  external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
