apiVersion: v2
name: dead-drop
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: app-template
    repository: https://bjw-s.github.io/helm-charts
    version: 3.3.0
