apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gitlab-secret-store
  annotations:
    helm.sh/hook: "post-install,post-upgrade"
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-secret
            namespace: external-secrets
            key: token
      projectID: "34242337"
