apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformRepository
metadata:
  name: {{ .Values.repository.name }}
spec:
  repository:
    url: {{ .Values.repository.url }}
    secretName: {{ .Values.repository.secretName }}
  overrideRunnerSpec:
    {{- toYaml .Values.repository.overrideRunnerSpec | nindent 4 }}
