{{- range .Values.layers }}
apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformLayer
metadata:
  name: {{ .name }}
spec:
  terraform:
    version: {{ .terraformVersion | default $.Values.global.terraformVersion | quote }}
    {{- with .terragrunt }}
    terragrunt:
      enabled: {{ .enabled }}
      version: {{ .version  | default $.Values.global.terragruntVersion | quote }}
    {{- end }}
  path: {{ .path }}
  branch: {{ .branch | default $.Values.global.branch | quote }}
  remediationStrategy: {{ .remediationStrategy | default "dry" | quote }}
  repository:
    name: {{ $.Values.repository.name }}
    namespace: {{ $.Values.global.namespace }}
  {{- with .overrideRunnerSpec }}
  overrideRunnerSpec:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
