apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-gitlab-repository-credentials
  namespace: argocd
spec:
  encryptedData:
    sshPrivateKey: AgB9ktoIlmmy2zFxqR/oLWqhqDkQoGn0LXqzOg6GmJCvMERF65az1wb6pIkH5FfJWv91msWaXWoA58YTbH825z2z7Dj3SM+5qD8kqEFK7ZGfRywcFZi5va6tLYlTn5TbD6E48xBU75mCStHkSkPwz83sabKuALhW/k5T7Ll/6qQeY6FuQrkz+lVzPxYSzk0JJSoV+RchSit/o5gicqzJgAvoyoThq6zLlEetz/RiL8Jc0d4X5WjUqLtr/+jENMOPi41HXHSKNkNSxqOgRNhGD/u38su4vqSD0p6nxB9PnNnIX5J931FEN8Dks3bnwmmZMlEzxd4diZZnOcsXIq7Y3xL8Ot3Y0Ni51AinooQHpumY/MwG9NN/pih8QMha+XbH5YHXcs2eiAQdy2ykQFzqaZdt+AKj98w15XusBEXEWvz/9Q/oyoYdL5AKAuTGTUYBmiYCO2BJp0M8WL4i4IYGVOuoBcWlimXFZ5CdsTteLDwnZCkuGzXO7L3FCWv7UbSdt/4K+CR4s9jd+z7DKlHm0B2OFdeF8idfVSJszihh1nv0VeC1MwQuJC/ylpvqup9zV72IoKyPK2nUvNViVuVz8cheKjkG7JNMpXMdKjPyKEYsrMnzfIYcjh5EJ6u7YIZW37LKshrjuaI1ZZv9N4Qtvj2wnzTgvq4kz7h9e0EiR7V/LdTUGZtqe34TFSOpSMzfhgglIYsNdgP3e4bkfPqQ0lQ7evj/UFC6FowhB+bjOXJhTNJyPbKcDRDqYVgtya2m1sSbU1Oo8EazWcCac1wbBPaKq6cIT7aKZN2BlS9i1Z6NdRGSQW66iXadL8E8jbjttzpI3WXpJSi5rl8YVtMI8YQdZJk+rqkruc6nfMdP7kuZ4SgI08xBwv8O6Y+87yO4tk8P5TbzH1exe6sYfxvah3fBShVGHxgcNTAOxO+9lh9cDXyT6Daqe6PpAkM5da023mNZlIqrX14u+OKEKXjet09xowuj0nuY+g8uRdkGY6DAMViVpC7jSOBTRlZ3VcwQJYhxnbQ/yjDcX/hAK/YuGv7isKvgndwRwWHpVo0wCGGnv0dHLau5H6ty5DXD77GmA9kRk/UIQ6NjpGofC8XAH10wbgPBuTQisdrTxgx9Cengc+23CWrsswv2CgRnUJNkrTA2nTH/PVhkg7+HUbgX7e0wOKLlnBFUF8X2caAXexqO95pxXVDCyfgjXtMK8TueEtrCK6Kvw73y+OrB6iIwn44=
    url: AgB7/8OoMR4l5eugzCYnj1rAPWee70U/V8xRqJ6WllDMMGLVuXcSQ+tyca1NmWy8FDULEgwq/VA2g3WCkuSMbca6jvSaj6kpKnvpebxTu/dZMLuRVFcP22M6E36B7PsedcN0T2izQGqC9iKzR+FG2KKGpFZnYwAapO6YIhUX4jRtBvkwg1Dskhrr/FfshswePVrWH02lPksiqdtpbT9nWnhfLzDxJshgZxsNaejBPOjwv/a9H1pEshlb369EHA9zzYowQDJyVCuYsqxfr/tVH0xPb7KEYb1AsFlwIg07Eid218lCH26VZNGAGsHa78w+kNMYo+XpxYyNQLEag1DAwlnbYotHqjeFWodE9amfduQYaGQrg6iMLVgHhdlmNVIiA5z8vu4tpEvCgsFEk4C+QqiUVKRUHDmGftBhC69Q3ApFSN71yTMLn++/F290DfNAnulXNjIjkU1rucdI4lVyb51dlWHub3pb8DSArtEIxTZljcrSBIV56wVLpBv6d0byupP0eNCu15Ayqmsixi1zuQ3cpI/TsySexMCdOEEiYL1gJNqCA4V3acWvkIoPCcJJXCT0QRPeeGSvRwQs+BveYOUqeI06akPryeP9FeRcoZXtke0EpWWGHfm/Nh/a4HvzjtQQprcoa00e2CrxrQmkk3AhUjisEKiB3A+q9lVDkwW++OcOOFsuiJ7WRHWG++wQxPDl2C/1/DFEQfYsGaj8D0z2UuI8WWcAyVE0jlbHFzMJxv4kIgHJz3xi
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: argo-gitlab-repository-credentials
      namespace: argocd
    type: Opaque

