# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  config.yaml: |
    tunnel: homelab-k8s
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: "*.terence.cloud"
      service: https://ingress-nginx-controller.ingress-nginx.svc.cluster.local
      originRequest:
        # Needed to prevent 502 errors when using ingress-nginx
        noTLSVerify: true
    - service: http_status:404
