# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
app-template:
  defaultPodOptions:
    automountServiceAccountToken: false

  controllers:
    # Configure the main controller
    main:
      type: deployment
      annotations:
        reloader.stakater.com/auto: "true"

      containers:
        # Configure the main application container
        main:
          image:
            repository: corentinth/it-tools
            tag: 2024.5.13-a0bc346
          env:
            TZ: Europe/Paris
          ports:
            - name: http
              containerPort: 80
          probes:
            liveness:
              enabled: true
              type: HTTP
            readiness:
              enabled: true
              type: HTTP
  service:
    # Configure a service for the main application
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 8080

  ingress:
    # Configure an Ingress for the main application
    main:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: it-tools
        gethomepage.dev/description: Collection of handy online tools for developers
        gethomepage.dev/group: Tooling
        gethomepage.dev/icon: it-tools
      className: "nginx"
      hosts:
        - host: &host tools.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: tools-tls
          hosts:
            - *host
