metallb:
  configInline:
    address-pools:
      - name: default
        protocol: layer2
        addresses:
          - 192.168.1.240-192.168.1.255
  prometheus:
    podMonitor:
      enabled: true
