applications:
  - name: argocd
    enabled: false
    annotations:
      argocd.argoproj.io/sync-wave: "2"
    source:
      repoURL: git@github.com:cterence/argo.git
      path: applications/argocd
      targetRevision: HEAD
    destination:
      namespace: argocd
  - name: kube-prometheus-stack-crds
    enabled: true
    annotations:
      argocd.argoproj.io/sync-wave: "1"
    source:
      repoURL: https://github.com/prometheus-community/helm-charts.git
      path: charts/kube-prometheus-stack/crds/
      targetRevision: kube-prometheus-stack-34.1.1
      directory:
        recurse: true
    syncOptions:
      - Replace=true
    destination:
      namespace: monitoring
