prometheus-blackbox-exporter:
  config:
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
      http_2xx_insecure:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
          follow_redirects: true
          preferred_ip_protocol: "ip4"
          tls_config:
            insecure_skip_verify: true
  prometheusRule:
    enabled: false
  serviceMonitor:
    enabled: true
    selfMonitor:
      enabled: true
    targets:
      - name: argocd
        url: http://argocd-server.argocd/healthz?full=true
        module: http_2xx_insecure
      - name: grafana
        url: http://kube-prometheus-stack-grafana.monitoring/api/health
        module: http_2xx
  configReloader:
    enabled: true
