prometheus-blackbox-exporter:
  prometheusRule:
    enabled: true
  podMonitoring:
    enabled: true
    selfMonitor:
      enabled: true
    targets:
      - name: argocd
        url: http://argocd-server.argocd/healthz?full=true
        module: http_2xx
      - name: grafana
        url: http://kube-prometheus-stack-grafana.monitoring/api/health
        module: http_2xx
  configReloader:
    enabled: true
