loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
    config:
      compactor:
        retention_enabled: true
      limits_config:
        retention_period: 3d
      table_manager:
        retention_deletes_enabled: true
        retention_period: 3d

    serviceMonitor:
      enabled: true
      prometheusRule:
        enabled: false

  promtail:
    enabled: true
    serviceMonitor:
      enabled: true
