loki-stack:
  loki:
    enabled: true

    persistence:
      enabled: true

    serviceMonitor:
      enabled: true
      prometheusRule:
        enabled: false

  promtail:
    enabled: true
    serviceMonitor:
      enabled: true
