loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
    loki:
      compactor:
        retention_enabled: true
      limits_config:
        retention_delete_enabled: true
        retention_period: 3d

    serviceMonitor:
      enabled: true
      prometheusRule:
        enabled: false

  promtail:
    enabled: true
    serviceMonitor:
      enabled: true
