apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vui-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: vui-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ `{{ .access_key }}` }}"
        AWS_SECRET_ACCESS_KEY: "{{ `{{ .secret_key }}` }}"
        SECURITY_TOKEN_KEY: "{{ `{{ .token_key }}` }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: velero_backblaze_access_key_id
    - secretKey: secret_key
      remoteRef:
        key: velero_backblaze_secret_access_key
    - secretKey: token_key
      remoteRef:
        key: velero_ui_security_token_key
