apiVersion: v2
name: opentelemetry-collector
description: A helm chart for an app
type: application
version: 0.1.0
dependencies:
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.102.1
