loki:
  deploymentMode: SingleBinary
  loki:
    auth_enabled: false
    compactor:
      retention_enabled: true
      delete_request_store: filesystem
    limits_config:
      retention_period: 3d
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
    schemaConfig:
      configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem
        schema: v13
  singleBinary:
    replicas: 1
  read:
    replicas: 0
  backend:
    replicas: 0
  write:
    replicas: 0
