apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gitlab-oauth2-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: gitlab-oauth2-credentials
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef: 
        key: gitlab_oauth2_credentials_client_id
    - secretKey: client_secret
      remoteRef:
        key: gitlab_oauth2_credentials_client_secret
    - secretKey: cookie_secret
      remoteRef: 
        key: gitlab_oauth2_credentials_cookie_secret
