firefly-iii-stack:
  firefly-db:
    enabled: false

  firefly-iii:
    enabled: true
    config:
      envValueFrom:
        DB_HOST:
          secretKeyRef:
            name: firefly-iii-cnpg-cluster-app
            key: host
        DB_PORT:
          secretKeyRef:
            name: firefly-iii-cnpg-cluster-app
            key: port
        DB_DATABASE:
          secretKeyRef:
            name: firefly-iii-cnpg-cluster-app
            key: dbname
        DB_USERNAME:
          secretKeyRef:
            name: firefly-iii-cnpg-cluster-app
            key: username
        DB_PASSWORD:
          secretKeyRef:
            name: firefly-iii-cnpg-cluster-app
            key: password
      env:
        DB_CONNECTION: pgsql
        DEFAULT_LANGUAGE: "fr_FR"
        DEFAULT_LOCALE: "equal"
        TZ: "Europe/Paris"
        TRUSTED_PROXIES: "**"

  importer:
    enabled: true

cnpg-cluster:
  type: postgresql
  mode: standalone
  version:
    postgresql: "16"
  cluster:
    instances: 1
    imageName: "ghcr.io/cloudnative-pg/postgresql:16.3" # Default value depends on type (postgresql/postgis/timescaledb)
    storage:
      size: 10Gi
    walStorage:
      enabled: true
    resources: {}
    primaryUpdateMethod: switchover
    primaryUpdateStrategy: unsupervised
    logLevel: "info"
    roles: []
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
    initdb:
      database: firefly-iii
