firefly-iii-stack:
  firefly-db:
    enabled: false

  firefly-iii:
    enabled: true
    config:
      envValueFrom:
        DB_HOST:
          secretKeyRef:
            name: firefly-iii-cnpg-cluster-app
            key: host
        DB_PORT:
          secretKeyRef:
            name: firefly-iii-cnpg-cluster-app
            key: port
        DB_DATABASE:
          secretKeyRef:
            name: firefly-iii-cnpg-cluster-app
            key: dbname
        DB_USERNAME:
          secretKeyRef:
            name: firefly-iii-cnpg-cluster-app
            key: username
        DB_PASSWORD:
          secretKeyRef:
            name: firefly-iii-cnpg-cluster-app
            key: password
      env:
        DB_CONNECTION: pgsql
        DEFAULT_LANGUAGE: "fr_FR"
        DEFAULT_LOCALE: "equal"
        TZ: "Europe/Paris"
        TRUSTED_PROXIES: "**"
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
        # nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
        # nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
      hosts:
        - ff.terence.cloud
      tls:
        - secretName: firefly-iii-tls
          hosts:
            - ff.terence.cloud

  importer:
    enabled: true
    fireflyiii:
      url: "https://ff.terence.cloud"
      vanityUrl: "https://ff.terence.cloud"
    config:
      env:
        IGNORE_DUPLICATE_ERRORS: "false"
        TZ: "Europe/Paris"

cnpg-cluster:
  type: postgresql
  mode: standalone
  version:
    postgresql: "16"
  cluster:
    instances: 1
    imageName: "ghcr.io/cloudnative-pg/postgresql:16.3" # Default value depends on type (postgresql/postgis/timescaledb)
    storage:
      size: 10Gi
    walStorage:
      enabled: true
    resources: {}
    primaryUpdateMethod: switchover
    primaryUpdateStrategy: unsupervised
    logLevel: "info"
    roles: []
    monitoring:
      enabled: true
      podMonitor:
        enabled: true
    initdb:
      database: firefly-iii
