apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atlantis-gitlab-credentials
spec:
  
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: atlantis-gitlab-credentials
    creationPolicy: Owner
  data:
    - secretKey: gitlab_secret
      remoteRef: 
        key: atlantis_gitlab_credentials_gitlab_secret
    - secretKey: gitlab_token
      remoteRef: 
        key: atlantis_gitlab_credentials_gitlab_token
