# Resources
region: eu-west-3

bastion:
  name: bastion
  imageId: ami-0042da0ea9ad6dd83
  instanceType: t3a.nano

securityGroups:
  name: compute
  labels:
    group: compute

eks:
  cluster:
    name: eks-cluster
    version: "1.21"
  nodes:
    name: eks-nodes
    blue:
      name: blue
      version: "1.21"
      diskSize: 8
      instanceTypes:
        - t3.micro
      capacityType: SPOT
      scalingConfig:
        minSize: 1
        maxSize: 2
        desiredSize: 1
    green:
      name: green
      version: "1.21"
      diskSize: 8
      instanceTypes:
        - t3.micro
      capacityType: SPOT
      scalingConfig:
        minSize: 1
        maxSize: 2
        desiredSize: 1

vpc:
  name: techradar
  cidrBlock: 10.0.0.0/16

subnets:
  private:
    name: private
    labels:
      type: private
  public:
    name: public
    labels:
      type: public

gateways:
  internet:
    name: igw
  nat:
    name: ngw
    eip:
      name: eip

routeTables:
  name: rtb

rds:
