longhorn:
  persistence:
    defaultClass: true
    defaultFsType: ext4
    reclaimPolicy: Delete

  defaultSettings:
    backupTarget: s3://longhorn-backup-tch@eu-central-003/
    backupTargetCredentialSecret: backup-credentials

  ingress:
    enabled: true
    ingressClassName: nginx
    host: longhorn.terence.cloud
    tls: true
    tlsSecret: longhorn-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/target: homelab.terence.cloud
      nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
      nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
