{{ range $externalEndpoint := .Values.externalEndpoints }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $externalEndpoint.name }}
  labels:
    name: {{ $externalEndpoint.name }}
  {{- if $externalEndpoint.ingressAnnotations }}
  annotations:
    {{- toYaml $externalEndpoint.ingressAnnotations | nindent 6 }}
  {{- end }}
spec:
  rules:
    - host:  {{ $externalEndpoint.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ $externalEndpoint.name }}
                port:
                  number: {{ $externalEndpoint.port }}
  tls:
    - hosts:
        -  {{ $externalEndpoint.host }}
      secretName:  {{ $externalEndpoint.host }}-tls
  ingressClassName: nginx
---
{{- end }}
