# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.4.0/charts/library/common/values.schema.json
app-template:
  defaultPodOptions:
    automountServiceAccountToken: false
    securityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
  configMaps:
    config:
      data:
        config.yaml: |
          name: homelab
          version: 1.0
          timeout: 5
          urls:
            - https://argocd.terence.cloud/healthz?full=true
            - https://bw.terence.cloud/alive
            - https://calibre.terence.cloud
            - https://grafana.terence.cloud/api/health
            - https://httpbin.terence.cloud/health
            - https://immich.terence.cloud/api/server/ping
            - https://next.terence.cloud/status.php
            - https://paperless.terence.cloud
            - http://oauth2-proxy.oauth2-proxy/ping

  controllers:
    main:
      type: deployment
      annotations:
        reloader.stakater.com/auto: "true"

      containers:
        main:
          image:
            repository: ghcr.io/cterence/go-healthcheck
            tag: main
          env:
            TZ: Europe/Paris
          ports:
            - name: http
              containerPort: 3000
          probes:
            liveness:
              enabled: true
              custom: true
              spec:
                httpGet:
                  port: http
                  path: /status
            readiness:
              enabled: true
              type: HTTP
              spec:
                httpGet:
                  port: http
                  path: /status
  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 3000

  ingress:
    main:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/target: home.terence.cloud
      className: "nginx"
      hosts:
        - host: &host health.terence.cloud
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: health-tls
          hosts:
            - *host

  persistence:
    config:
      type: configMap
      name: config
      advancedMounts:
        main:
          main:
            - path: /
