apiVersion: v2
name: argocd
description: Declarative, GitOps continuous delivery tool for Kubernetes
type: application
version: 3.33.1
dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 7.4.4
