apiVersion: config.terraform.padok.cloud/v1alpha1
kind: TerraformLayer
metadata:
  name: random-pets
  namespace: burrito
spec:
  terraformVersion: "1.3.1"
  path: "burrito-test"
  branch: "main"
  remediationStrategy: "autoApply"
  repository:
    kind: TerraformRepository
    name: twig
    namespace: burrito
