name: Update deployed apps table

on:
  push:
    paths:
      - argocd-apps/applicationset.yaml
      - k8s-apps/*

jobs:
  update-deployed-apps-table:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: mikefarah/yq
      - name: Update deployed apps table
        run: ./scripts/update-deployed-apps.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'docs: [ci] updated deployed apps table'
          add: 'README.md'
