name: Update deployed apps table

on:
  push:
    paths:
      - argocd-apps/applicationset.yaml
      - k8s-apps/**

jobs:
  update-deployed-apps-table:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Filter paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            argocd-apps:
              - 'argocd-apps/**'
            k8s-apps:
              - deleted: 'k8s-apps/**'
      - name: Update deployed apps table
        if: steps.filter.outputs.argocd-apps == 'true' || steps.filter.outputs.k8s-apps == 'true'
        run: ./scripts/update-deployed-apps.sh
      - name: Commit changes
        if: steps.filter.outputs.argocd-apps == 'true' || steps.filter.outputs.k8s-apps == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'docs: [ci] updated deployed apps table'
          add: 'README.md'
