name: Update deployed apps table

on:
  push:
    paths:
      - argocd-apps/applicationset.yaml

jobs:
  update-deployed-apps-table:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update deployed apps table
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
          ./scripts/update-deployed-apps.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'docs: updated deployed apps table'
          add: 'README.md'
