apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-credentials
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgBRtTLL7Janqtdb5WpFhBn5q+M5NVr2hZpFsZENvNStSlyRLS7S1T4TxRwzmiDoQT9ibeCrELZ5o5lhsSTwRcBh5k9f2MjgtOKsaqA1LP0Pz0yU9rc26aVSZS+dQXY71mu9sOIrQB5hiIN05LURvfh1rzPCVmwtvvwAoMXIYQlr6qkTQhfjDj3i8+4UPbmiX/KMt1eoQ8l0mW0kd2zVKgArC+TFFguITYP3+ipXywzP6iIQ8dUvscCA628OX93a2onzSTfbnybHUFsyaLCr8GzlRCi4CRLJcaWSUvPfyfWrLVLi41Wn63YbXj6qrDklf7WXro65/GAk4QJGuZuhczwGG/bs3o0A/OaO9UUA6rX/X1EzIatiqOLKkbefyPRuF6nGOVUi/4IXylIBVrV0IaBmNOD9jqxNza9bbXVpgFt7jOjZqm5lDccO1L+sDMpGiTzYfuqLBIAwtX9HOVES3zRXs7odDZ0To+A2P87iKgT1DkGQSfbxxwRRVLK7x/tDGa01aKWgJFkgD5J5o6OLx0UfwDAG0p7AKl4l91YdQrIoXFP7+/ITmsdJ9AiHlAknbZUQqYCAmFjBLzrqrcWaSzRDNILIJ6aJd4wPmeW1ocJXp6V21weryIOv0sS8CG2xUbnmnDP4vY4yNbhh3Q/Jtm9zhBxrA66g5ehpikQhgOygaUEfKGO5pW+iAtBIHEhyr1fdT1H609417lElwdWtBd3a0Jx6p4E9k6zXqydPzO1aYgmDIqOPyEne
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-credentials
      namespace: external-dns
    type: Opaque

